# 
# Synthesis run script generated by Vivado
# 

create_project -in_memory -part xc7a100tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/Users/merli/Desktop/project_V1_maj/project_V1_maj.cache/wt [current_project]
set_property parent.project_path C:/Users/merli/Desktop/project_V1_maj/project_V1_maj.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_cache_permissions disable [current_project]
read_vhdl -library xil_defaultlib {
  C:/Users/merli/Desktop/project_V1_maj/project_V1_maj.srcs/sources_1/imports/PmodJSTK_Demo/Binary_To_BCD.vhd
  C:/Users/merli/Desktop/project_V1_maj/project_V1_maj.srcs/sources_1/imports/PmodJSTK_Demo/ClkDiv_5Hz.vhd
  C:/Users/merli/Desktop/project_V1_maj/project_V1_maj.srcs/sources_1/imports/PmodJSTK_Demo/ClkDiv_66_67kHz.vhd
  C:/Users/merli/Desktop/project_V1_maj/project_V1_maj.srcs/sources_1/imports/PmodJSTK_Demo/PmodJSTK.vhd
  C:/Users/merli/Desktop/project_V1_maj/project_V1_maj.srcs/sources_1/imports/PmodJSTK_Demo/spiCtrl.vhd
  C:/Users/merli/Desktop/project_V1_maj/project_V1_maj.srcs/sources_1/imports/PmodJSTK_Demo/spiMode0.vhd
  C:/Users/merli/Desktop/project_V1_maj/project_V1_maj.srcs/sources_1/imports/PmodJSTK_Demo/ssdCtrl.vhd
  C:/Users/merli/Desktop/project_V1_maj/project_V1_maj.srcs/sources_1/imports/PmodJSTK_Demo/PmodJSTK_Demo.vhd
  C:/Users/merli/Desktop/project_V1_maj/project_V1_maj.srcs/sources_1/new/coor_voiture.vhd
  C:/Users/merli/Desktop/project_V1_maj/project_V1_maj.srcs/sources_1/new/descente.vhd
  C:/Users/merli/Desktop/project_V1_maj/project_V1_maj.srcs/sources_1/new/game_over.vhd
  C:/Users/merli/Desktop/project_V1_maj/project_V1_maj.srcs/sources_1/new/gestion_clock.vhd
  C:/Users/merli/Desktop/project_V1_maj/project_V1_maj.srcs/sources_1/new/gestion_input.vhd
  C:/Users/merli/Desktop/project_V1_maj/project_V1_maj.srcs/sources_1/new/master.vhd
  C:/Users/merli/Desktop/project_V1_maj/project_V1_maj.srcs/sources_1/new/menu.vhd
  C:/Users/merli/Desktop/project_V1_maj/project_V1_maj.srcs/sources_1/new/mux.vhd
  C:/Users/merli/Desktop/project_V1_maj/project_V1_maj.srcs/sources_1/new/nouv_decors.vhd
  C:/Users/merli/Desktop/project_V1_maj/project_V1_maj.srcs/sources_1/new/pmodoledrgb_bitmap.vhd
  C:/Users/merli/Desktop/project_V1_maj/project_V1_maj.srcs/sources_1/new/routing.vhd
}
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/Users/merli/Desktop/project_V1_maj/project_V1_maj.srcs/constrs_1/new/NEXYS4pasDDR.xdc
set_property used_in_implementation false [get_files C:/Users/merli/Desktop/project_V1_maj/project_V1_maj.srcs/constrs_1/new/NEXYS4pasDDR.xdc]


synth_design -top routing -part xc7a100tcsg324-1


write_checkpoint -force -noxdef routing.dcp

catch { report_utilization -file routing_utilization_synth.rpt -pb routing_utilization_synth.pb }
